/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        spotify: {
          green: '#1DB954',
          'green-hover': '#1ED760',
          'green-active': '#169C46',
          purple: '#8B5CF6',
          black: '#000000',
          'dark-charcoal': '#121212',
          'dark-gray': '#282828',
          'dark-surface': '#181818',
          'medium-gray': '#6A6A6A',
          'light-gray': '#B3B3B3',
          white: '#FFFFFF',
          'link-blue': '#5E9FFF',
          success: '#1DB954',
          warning: '#FFA726',
          error: '#F44336',
          info: '#29B6F6',
        },
      },
      fontFamily: {
        inter: ['var(--font-inter)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        poppins: ['var(--font-poppins)', 'var(--font-inter)', 'sans-serif'],
        mono: ['JetBrains Mono', 'Courier New', 'monospace'],
      },
      fontSize: {
        'h1': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'h1-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'h2': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2-mobile': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'h3-mobile': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'h4': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'h4-mobile': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'h5': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
        'h6': ['14px', { lineHeight: '1.5', letterSpacing: '0.01em', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '1.6' }],
        'body-mobile': ['15px', { lineHeight: '1.6' }],
        'body-small': ['14px', { lineHeight: '1.6' }],
        'body-small-mobile': ['13px', { lineHeight: '1.6' }],
        'caption': ['12px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        'caption-mobile': ['11px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
      },
      spacing: {
        '18': '72px',
        '22': '88px',
        '26': '104px',
      },
      boxShadow: {
        'sm': '0 2px 4px rgba(0, 0, 0, 0.3)',
        'md': '0 4px 12px rgba(0, 0, 0, 0.4)',
        'lg': '0 8px 24px rgba(0, 0, 0, 0.5)',
        'xl': '0 16px 48px rgba(0, 0, 0, 0.6)',
        'green': '0 4px 12px rgba(29, 185, 84, 0.3)',
        'green-lg': '0 8px 24px rgba(0, 0, 0, 0.5)',
      },
      backdropBlur: {
        'light': '4px',
        'medium': '8px',
        'heavy': '16px',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '250ms',
        'slow': '400ms',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'decelerate': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'accelerate': 'cubic-bezier(0.4, 0.0, 1, 1)',
        'sharp': 'cubic-bezier(0.4, 0.0, 0.6, 1)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(180deg, #282828 0%, #000000 100%)',
        'gradient-header': 'linear-gradient(180deg, rgba(29, 185, 84, 0.8) 0%, rgba(0, 0, 0, 0) 100%)',
        'gradient-card': 'linear-gradient(135deg, #282828 0%, #181818 100%)',
        'gradient-overlay': 'linear-gradient(180deg, transparent 0%, rgba(0, 0, 0, 0.8) 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 300ms ease-in-out',
        'slide-up': 'slideUp 400ms ease-out',
        'scale-in': 'scaleIn 200ms ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
